controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: fitxak_index
        permanent: true
